### PR TITLE
compile_macro.py, initial version

### PR DESCRIPTION
**Pull request by klenze**
compile_macro.py, a beta quality heuristic macro compiler.

### CODE REVIEW

**Comment by kresan** [comment]
Could you please shortly describe what is the idea behind? For which application do we need it?

**Comment by klenze** [comment]
Sorry for the delay. Running macros with CINT has -- in my experience -- the drawback that they are less debugable than compiled C++. Compiling them with e.g. "root foo.C+" solves some of these issues, but involves inserting all the header files into each macro. 

The approach I chose here is different: For the locations of ROOT, FairROOT, R3BROOT, I create a database of all header files and library symbols. 

Then I heuristically check which headers the program will probably need. If I have found a header TFoo.h somewhere and the macro contains the text TFoo somewhere, it will probably need that header. (If TFoo.h defines TBar, I will not check for that, as it would mean parsing the header. A better way to deal with this might be to compile the header and remember the symbols declared in the object file. Not really trivial, though.)

Afterwards, I compile a wrapper file containing both my includes and the macro. 

Then, I look in the object file for undefined symbols and try to match them up with libraries where they are defined. This tells me which libraries I will have to link against.

**Comment by klenze** [comment]
I updated the compile_macro.py script to be a bit more robust. 

Also, I found and reported https://sft.its.cern.ch/jira/browse/ROOT-10499 , which means that any compiled code (using std::cout) which executes macros (e.g. g4Config.C) which also use cout (again, e.g. g4Config.C) will result in segfaults. Probably because of C++ ABI incompatibilities between gcc and llvm. 

As a workaround, we might want to try to use printfs instead of cout in these macros. 

If inclusion in /r3b is deemed undesirable, I am also willing to hide the python script somewhere deep within the califa directories, but I would really ask for this PR to be merged. Personally, one in a while when I try to run a macro with root, roots clang spews tens of kilobytes of headers to stdout and complains about unexisting syntax errors. As the whole implicit compilation process used to parse macros the root way is very opaque, it is hard to debug. 

This script instead compiles macros as traditional C++ and actually tells you about the steps it executes.

**Comment by kresan** [comment]
please squash the commits

**Comment by kresan** [comment]
merged with 06af97d

**Pull request closed without merging**
